[package]
name = "sel4-rust"
version = "0.1.0"
authors = ["pdlan <pengdinglan@gmail.com>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[lib]
crate-type = ["staticlib"]

[features]
smp = []