/*
 * Copyright 2014, General Dynamics C4 Systems
 *
 * This software may be distributed and modified according to the terms of
 * the GNU General Public License version 2. Note that NO WARRANTY is provided.
 * See "LICENSE_GPLv2.txt" for details.
 *
 * @TAG(GD_GPL)
 */

/* This header was generated by kernel/tools/syscall_header_gen.py.
 *
 * To add a system call number, edit kernel/include/api/syscall.xml
 *
 */
#ifndef __ARCH_API_SYSCALL_H
#define __ARCH_API_SYSCALL_H

#ifdef __ASSEMBLER__

/* System Calls */
#define SYSCALL_CALL (-1)
#define SYSCALL_REPLY_RECV (-2)
#define SYSCALL_SEND (-3)
#define SYSCALL_NB_SEND (-4)
#define SYSCALL_RECV (-5)
#define SYSCALL_REPLY (-6)
#define SYSCALL_YIELD (-7)
#define SYSCALL_NB_RECV (-8)

#endif

#define SYSCALL_MAX (-1)
#define SYSCALL_MIN (-8)

#ifndef __ASSEMBLER__

enum syscall {
    SysCall = -1,
    SysReplyRecv = -2,
    SysSend = -3,
    SysNBSend = -4,
    SysRecv = -5,
    SysReply = -6,
    SysYield = -7,
    SysNBRecv = -8,
#if defined CONFIG_PRINTING
    SysDebugPutChar = -9,
    SysDebugDumpScheduler = -10,
#endif /* defined CONFIG_PRINTING */
#if defined CONFIG_DEBUG_BUILD
    SysDebugHalt = -11,
    SysDebugCapIdentify = -12,
    SysDebugSnapshot = -13,
    SysDebugNameThread = -14,
#endif /* defined CONFIG_DEBUG_BUILD */
#if defined CONFIG_DANGEROUS_CODE_INJECTION
    SysDebugRun = -15,
#endif /* defined CONFIG_DANGEROUS_CODE_INJECTION */
#if defined CONFIG_ENABLE_BENCHMARKS
    SysBenchmarkFlushCaches = -16,
    SysBenchmarkResetLog = -17,
    SysBenchmarkFinalizeLog = -18,
    SysBenchmarkSetLogBuffer = -19,
    SysBenchmarkNullSyscall = -20,
#endif /* defined CONFIG_ENABLE_BENCHMARKS */
#if defined CONFIG_BENCHMARK_TRACK_UTILISATION
    SysBenchmarkGetThreadUtilisation = -21,
    SysBenchmarkResetThreadUtilisation = -22,
#endif /* defined CONFIG_BENCHMARK_TRACK_UTILISATION */
#if defined CONFIG_KERNEL_X86_DANGEROUS_MSR
    SysX86DangerousWRMSR = -23,
    SysX86DangerousRDMSR = -24,
#endif /* defined CONFIG_KERNEL_X86_DANGEROUS_MSR */
#if defined CONFIG_VTX
    SysVMEnter = -25,
#endif /* defined CONFIG_VTX */
};
typedef word_t syscall_t;

/* System call names */
#ifdef CONFIG_DEBUG_BUILD
static char *syscall_names[] UNUSED = {
         [1] = "Call",
         [2] = "ReplyRecv",
         [3] = "Send",
         [4] = "NBSend",
         [5] = "Recv",
         [6] = "Reply",
         [7] = "Yield",
         [8] = "NBRecv",
};
#endif /* CONFIG_DEBUG_BUILD */
#endif

#endif /* __ARCH_API_SYSCALL_H */
