#![allow(non_camel_case_types)]

pub enum invocation_label {
    InvalidInvocation = 0,
    UntypedRetype = 1,
    TCBReadRegisters = 2,
    TCBWriteRegisters = 3,
    TCBCopyRegisters = 4,
    TCBConfigure = 5,
    TCBSetPriority = 6,
    TCBSetMCPriority = 7,
    TCBSetSchedParams = 8,
    TCBSetIPCBuffer = 9,
    TCBSetSpace = 10,
    TCBSuspend = 11,
    TCBResume = 12,
    TCBBindNotification = 13,
    TCBUnbindNotification = 14,
    TCBSetTLSBase = 15,
    CNodeRevoke = 16,
    CNodeDelete = 17,
    CNodeCancelBadgedSends = 18,
    CNodeCopy = 19,
    CNodeMint = 20,
    CNodeMove = 21,
    CNodeMutate = 22,
    CNodeRotate = 23,
    CNodeSaveCaller = 24,
    IRQIssueIRQHandler = 25,
    IRQAckIRQ = 26,
    IRQSetIRQHandler = 27,
    IRQClearIRQHandler = 28,
    DomainSetSet = 29,
    nInvocationLabels = 30,
}
